permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: 小8
  email: yangyucug@gmail.com
  link: http://baxiang123.com
  #weibo: http://weibo.com/yansu0711
  github: http://github.com/baxiang

# 站点信息
title: 小8的技术博客 
description: 小8的技术博客
url: http://baxiang123.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: https://avatars0.githubusercontent.com/u/2994323?v=2&s=460
favicon: https://avatars0.githubusercontent.com/u/2994323?v=2&s=460

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: suyan-zh

# 主题设置，自动激活某个标签
active: ios

# 首页除了最新文章外显示分类
cates: 
- ios
 # - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
